id: I15F49B56
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T16:33:44+00:00'
last_modified: '2022-06-07T22:35:45.515441+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7794
  title: གནམ་མཚོའི་ལོ་རྒྱུས་རིག་གནས་དཔེ་ཚོགས། ༼༣,༤,༥༽
  author: ''
  base:
    806C:
      image_group_id: I3CN8661
      title: ''
      total_pages: 510
      order: 1
      base_file: 806C.txt
    '0055':
      image_group_id: I3CN8662
      title: ''
      total_pages: 494
      order: 2
      base_file: 0055.txt
    1CE2:
      image_group_id: I3CN8663
      title: ''
      total_pages: 644
      order: 3
      base_file: 1CE2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
