id: P004399
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN7794
  title: གནམ་མཚོའི་ལོ་རྒྱུས་རིག་གནས་དཔེ་ཚོགས། ༼༣,༤,༥༽
  author: ''
  volumes:
    f1a4963e7e7d4198a38beffaed883e7a:
      image_group_id: I3CN8661
      title: ''
      volume_number: 1
      total_pages: 510
    fe8fce7b48b042cb92f5f10f30df4df2:
      image_group_id: I3CN8662
      title: ''
      volume_number: 2
      total_pages: 494
    2d0c7e6f967f498d9c8df1f9db65f971:
      image_group_id: I3CN8663
      title: ''
      volume_number: 3
      total_pages: 644
